name: Bach'

description: 'GitHub Action that executes Bach'

inputs:
  bach-action:
    description: 'Bach action to execute, defaults to build'
    required: true
    default: 'build'
  bach-version:
    description: 'Version of Bach to use, defaults to HEAD'
    required: true
    default: 'HEAD'

runs:
  using: 'composite'
  steps:
    - name: 'Print Java shell version'
      shell: bash
      run: jshell --version
    - name: 'Run Bach'
      shell: bash
      run: |
        version=$([[ ${{ inputs.bach-version }} = 'HEAD' ]] && echo '' || echo "@${{ inputs.bach-version }}")
        jshell https://sormuras.de/bach${version}/${{ inputs.bach-action }}
