name: 'Bach help'

description: "Print Bach's help screen"

inputs:
  bach-version:
    description: 'Version of Bach to use'
    required: true
    default: '11.9'

runs:
  using: "composite"
  steps:
    - run: jshell https://sormuras.de/bach@${{ inputs.bach-version }}/help
      shell: bash
