name: Bach.java

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: "Build (JDK-${{ matrix.java }}, ${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [15, 16-ea]
    runs-on: ${{ matrix.os }}
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v2
    - name: 'Setup JDK'
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: 'Build Bach.java'
      run: java .bach/src/build/build/Bootstrap.java

    - name: 'Upload build artifact'
      uses: actions/upload-artifact@v2
      with:
        name: artifact-${{ matrix.java }}-${{ matrix.os }}
        path: .bach/workspace/logbook.md

  publish_snapshot:
    name: 'Publish Snapshot'
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository == 'sormuras/bach' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: 'Setup JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: 'Set snapshot version'
      run: |
        SNAPSHOT="$(java src/bach/Version.java)+SNAPSHOT"
        java src/bach/Version.java ${SNAPSHOT}
        git diff
        echo ::set-env name=SNAPSHOT::${SNAPSHOT}

    - name: 'Build Bach.java'
      run: java .bach/src/build/build/Bootstrap.java

    - name: 'Publish snapshot to GitHub Packages'
      env:
        GITHUB_TOKEN: ${{ github.token }}
        DEPLOY: '--batch-mode --no-transfer-progress org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy-file'
        REPOSITORY: '-DrepositoryId=github -Durl=https://maven.pkg.github.com/sormuras/bach'
      run: for f in .bach/workspace/deploy/maven/*.files ; do mvn ${DEPLOY} ${REPOSITORY} $(cat ${f}) ; done
