name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 'List all -info.java files'
        run: find | grep \\-info.java | sort
      - name: 'Set up Java'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 22
      - name: 'Build Bach with Bach'
        run: java .bach/src/run.bach/run/Build.java
