name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: false
        default: 'Because...'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Download JDK'
        uses: sormuras/download-jdk@v1
        id: jdk
        with:
          feature: 16
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.jdk.outputs.version }}
          jdkFile: ${{ steps.jdk.outputs.file }}
      - name: 'Set up version'
        run: |
          SHA7=$(echo "${{ github.sha }}" | cut -c1-7)
          VERSION=16-ea+${SHA7}
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
      - name: 'Bootstrap Bach'
        run: java --show-version .bach/build/build/Bootstrap.java
      - name: 'Build Bach ${{ env.VERSION }}'
        run: |
          java \
            -Dbach.project.version=${VERSION} \
            -Dbach.project.main.jarslug=early-access \
            --module-path .bach/cache \
            --module com.github.sormuras.bach \
            build
      - name: 'Publish test summary'
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: .bach/workspace/reports/junit-test/*/*.xml
      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ env.VERSION }}
          path: |
            .bach/workspace/logbook.md
            .bach/workspace/modules
            .bach/workspace/documentation/api
      - name: 'Release early-access build'
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: 'early-access'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          title: "Bach ${{ env.VERSION }}"
          files: |
            .bach/workspace/modules/*.jar
