name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up latest JDK 17'
        uses: oracle-actions/setup-java@v1
      - name: 'Build Bach ${{ github.sha }}'
        run: java src/Bach.java build
      - name: 'Upload artifact ${{ github.event.repository.name }}-build-${{ github.sha }}'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ github.sha }}
          path: |
            LICENSE
