name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Build Bach with Bach ${{ github.sha }}'
        run: $JAVA_HOME_17_X64/bin/java .bach/bin/bach.java build
  quick-start-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Create an example project'
        run: |
          mkdir example && cd example
          echo 'Files.copy(URI.create("https://java.bach.run").toURL().openStream(), Files.createDirectories(Path.of(".bach/bin")).resolve("bach.java"))' | jshell -
          $JAVA_HOME_17_X64/bin/java .bach/bin/bach.java --verbose info
          cd .. && rm --recursive --force example
  quick-start-windows:
    runs-on: windows-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Create an example project'
        run: |
          mkdir example && cd example
          echo Files.copy(URI.create("https://java.bach.run").toURL().openStream(), Files.createDirectories(Path.of(".bach/bin")).resolve("bach.java")) | jshell -
          $JAVA_HOME_17_X64/bin/java .bach/bin/bach.java --verbose info
          cd .. && rmdir /Q /S example
        shell: cmd