name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up latest JDK'
        uses: oracle-actions/setup-java@v1
      - name: 'Run bach.java ${{ github.sha }}'
        run: java --show-version .bach/bin/bach.java --version
