name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Set up latest JDK'
        uses: oracle-actions/setup-java@v1
      - name: 'Build with Bach ${{ github.sha }}'
        run: .bach/bin/bach build
