name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Download JDK with Records'
        uses: sormuras/download-jdk@v1
        id: jdk
        with:
          feature: 16
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.jdk.outputs.version }}
          jdkFile: ${{ steps.jdk.outputs.file }}
      - name: 'Set up constants'
        run: |
          SHA7=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "VERSION=15-ea+${SHA7}" >> ${GITHUB_ENV}
      - name: 'Bootstrap Bach'
        run: java --show-version .bach/build/build/Bootstrap.java
      - name: 'Build Bach ${{ env.VERSION }}'
        run: java --module-path .bach/workspace/classes/.bootstrap --module build/build.Build ${VERSION}
      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ env.VERSION }}
          path: |
            .bach/workspace/modules
            .bach/workspace/documentation/api
