name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Build Bach with Bach ${{ github.sha }}'
        run: $JAVA_HOME_17_X64/bin/java bin/bach.java build
      - name: 'Upload artifact ${{ github.event.repository.name }}-build-${{ github.sha }}'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-build-${{ github.sha }}
          path: |
            .bach/out/*
            .bach/out/main/modules/*.jar
