name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  VERSION: "15-ea+${{ github.sha }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: 'Bootstrap Bach'
        run: java --show-version -Dbach.project.version=${VERSION} .bach/bootstrap/Bootstrap.java
      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ env.JDK_VERSION }}
          path: |
            .bach/workspace/modules
