name: Quick Start

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quick-start-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Set up latest JDK'
        uses: oracle-actions/setup-java@v1
      - name: 'Create an example project'
        run: |
          mkdir example && cd example
          echo 'Files.copy(URI.create("https://java.bach.run").toURL().openStream(), Files.createDirectories(Path.of(".bach/bin")).resolve("bach.java"))' | jshell -
          java .bach/bin/bach.java --verbose info
          cd .. && rm --recursive --force example
  quick-start-windows:
    runs-on: windows-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Set up latest JDK'
        uses: oracle-actions/setup-java@v1
      - name: 'Create an example project'
        run: |
          mkdir example && cd example
          echo Files.copy(URI.create("https://java.bach.run").toURL().openStream(), Files.createDirectories(Path.of(".bach/bin")).resolve("bach.java")) | jshell -
          java .bach/bin/bach.java --verbose info
          cd .. && rmdir /Q /S example
        shell: cmd
