name: Release
on:
  release:
    types: [ prereleased, released ]
env:
  VERSION: ${{ github.event.release.tag_name }}
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Download JDK with Records'
        uses: sormuras/download-jdk@v1
        id: jdk
        with:
          feature: 16
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.jdk.outputs.version }}
          jdkFile: ${{ steps.jdk.outputs.file }}
      - name: 'Bootstrap Bach'
        run: java --show-version .bach/build/build/Bootstrap.java
      - name: 'Build Bach ${{ env.VERSION }}'
        run: java --module-path .bach/workspace/classes/.bootstrap --module build/build.Build ${VERSION}
      - name: 'Upload module com.github.sormuras.bach@${{ env.VERSION }}'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .bach/workspace/modules/com.github.sormuras.bach@${{ env.VERSION }}.jar
          asset_name: com.github.sormuras.bach@${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
