name: Release

on:
  milestone:
    types: closed

jobs:
  release:
    if: github.event.milestone.open_issues == 0 && contains(github.event.milestone.description, '✔')
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v2

      - name: 'Configure git user'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: 'Set up Java (bintray)'
        uses: actions/setup-java@v1
        with: # https://github.com/actions/setup-java#publishing-using-apache-maven
          java-version: 14
          server-id: bintray-sormuras-maven
          server-username: BINTRAY_USERNAME
          server-password: BINTRAY_PASSWORD

      - name: 'Configure environment variables'
        run: |
          echo "github.actor=${{ github.actor }}"
          echo "github.sha=${{ github.sha }}"
          echo "github.event.milestone.number=${{ github.event.milestone.number }}"
          echo "github.event.milestone.title=${{ github.event.milestone.title }}"
          echo "github.event.milestone.closed_issues=${{ github.event.milestone.closed_issues }}"
          echo ::set-env name=VERSION::${{ github.event.milestone.title }}
          echo ::set-env name=PREVIOUS::$(java src/bach/Version.java)

      - name: 'Set version, diff, commit, tag'
        run: |
          java src/bach/Version.java ${VERSION}
          git diff
          git commit --all --message "Release Bach.java ${VERSION}"
          git tag ${VERSION}

      - name: 'Build Bach.java'
        run: java --show-version .bach/src/build/build/Bootstrap.java

      - name: 'Push release with new tag'
        run: git push origin master --tags

      - name: 'Create GitHub release'
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.milestone.title }}
          release_name: Bach.java ${{ github.event.milestone.title }}
          body: ${{ github.event.milestone.description }}
          draft: false
          prerelease: false

      - name: 'Upload module to GitHub release'
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: .bach/workspace/modules/de.sormuras.bach@${{ github.event.milestone.title }}.jar
          asset_name: de.sormuras.bach@${{ github.event.milestone.title }}.jar
          asset_content_type: application/java-archive

      - name: 'Publish to Bintray'
        env:
          BINTRAY_USERNAME: sormuras
          BINTRAY_PASSWORD: ${{ secrets.BINTRAY_KEY }}
          DEPLOY: '--batch-mode --no-transfer-progress org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy-file'
          REPOSITORY: '-DrepositoryId=bintray-sormuras-maven -Durl=https://api.bintray.com/maven/sormuras/maven/bach/;publish=1'
        run: for f in .bach/workspace/deploy/maven/*.files ; do mvn ${DEPLOY} ${REPOSITORY} $(cat ${f}) ; done

      - name: 'Restore previous version from environment variable'
        run: |
          java src/bach/Version.java ${PREVIOUS}
          git commit --all --message "Back to version ${PREVIOUS}"
          git push origin master
