name: Release
on:
  release:
    types: [ released ]
env:
  GITHUB_TOKEN: ${{ github.token }}
  VERSION: ${{ github.event.release.tag_name }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: 'Build Bach ${{ env.VERSION }}'
        run: |
          java --show-version \
            -Dbach.project.version=${VERSION} \
            .bach/bootstrap/Bootstrap.java
      - name: 'Upload module com.github.sormuras.bach@${{ env.VERSION }}'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .bach/workspace/modules/com.github.sormuras.bach@${{ env.VERSION }}.jar
          asset_name: com.github.sormuras.bach@${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
