name: Release

on:
  release:
    types: [ prereleased, released ]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      sha7: ${{ steps.version.outputs.sha7 }}
      sha8: ${{ steps.version.outputs.sha8 }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: 'Compute version string'
        id: version
        run: |
          SHA7=$(echo "${{ github.sha }}" | cut -c1-7)
          SHA8=$(echo "${{ github.sha }}" | cut -c1-8)
          echo "::set-output name=sha7::${SHA7}"
          echo "::set-output name=sha8::${SHA8}"
          echo "::set-output name=version::${{ github.event.release.tag_name }}"

  release:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Download JDK'
        uses: sormuras/download-jdk@v1
        id: jdk
        with:
          feature: 17
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.jdk.outputs.version }}
          jdkFile: ${{ steps.jdk.outputs.file }}
      - name: 'Bootstrap Bach'
        run: java --show-version .bach/build/build/Bootstrap.java
      - name: 'Build Bach ${{ needs.setup.outputs.version }}'
        run: |
          java \
            -Dbach.project.version=${{ needs.setup.outputs.version }} \
            --module-path .bach/cache \
            --module com.github.sormuras.bach \
            build
      - name: 'Upload module com.github.sormuras.bach@${{ env.VERSION }}'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .bach/workspace/modules/com.github.sormuras.bach@${{ needs.setup.outputs.version }}.jar
          asset_name: com.github.sormuras.bach@${{ needs.setup.outputs.version }}.jar
          asset_content_type: application/java-archive
